<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.1.2 (Python 3.7.3 on win32)" generated="20200126 20:11:17.052" rpa="false">
<suite id="s1" name="Demo3" source="E:\PythonWorkspace\RobotPy\Tests\Selenium\demo3.robot">
<test id="s1-t1" name="T1">
<kw name="openExcel">
<arguments>
<arg>E:\\PythonWorkspace\\RobotPy\\TestData\\data2.xlsx</arg>
</arguments>
<msg timestamp="20200126 20:11:17.110" level="FAIL">No keyword with name 'openExcel' found.</msg>
<status status="FAIL" starttime="20200126 20:11:17.110" endtime="20200126 20:11:17.110"></status>
</kw>
<status status="FAIL" starttime="20200126 20:11:17.108" endtime="20200126 20:11:17.111" critical="yes">No keyword with name 'openExcel' found.</status>
</test>
<status status="FAIL" starttime="20200126 20:11:17.054" endtime="20200126 20:11:17.113"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="Demo3">Demo3</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20200126 20:11:17.106" level="ERROR">Error in file 'E:\PythonWorkspace\RobotPy\Tests\Selenium\demo3.robot': Resource file '..\..\Resources\R1' does not exist.</msg>
</errors>
</robot>
